
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(SDK_LIB_BASE_DIR ${CMAKE_CURRENT_LIST_DIR}/debug)
else()
    set(SDK_LIB_BASE_DIR ${CMAKE_CURRENT_LIST_DIR}/release)
endif()
set(SDK_INCLUDE_BASE_DIR ${CMAKE_CURRENT_LIST_DIR}/include)

set(SDK_COMPILE_DEFINATIONS
    HCOMPRESS_BUILD_STATIC_LIBS
    HFONTAWESOME_BUILD_STATIC_LIBS
    HMATH_BUILD_STATIC_LIBS
    HMISC_BUILD_STATIC_LIBS
    HQT_BUILD_STATIC_LIBS
)
